# Site settings
title: DarkSun27
description: 'Porfolio Page'
url: ''
baseurl: 'darksun27.tech'
bkimage: '/images/tiled.webp'
profilepic: '/images/display_picture.png'
fontawesome: '/js/fa.js'
resume: '/resume/SiddharthBatraResume.pdf'

author:
  name: 'DarkSun27'
  email: sbsiddharth@gmail.com
  twitter_username: darksun2798
  github_username:  darksun27
  linkedin_username:  darksun27

# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

#plugins: ['jekyll-paginate']
exclude: ['README.md', 'screenshot-overview.png']
